Repository sygmaprotocol/sygma-sdk, pull requests merged in 2024-09, with the labels that each got.

#509 chore(main): release core 1.0.3
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#511 chore(main): release core 1.1.0
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#513 chore(main): release evm 1.1.0
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending

#512 chore(main): release utils 1.1.0
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  release-please/rp-utils-manifest.json
Labels: autorelease: pending

#517 chore(main): release core 1.2.0
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#516 chore(main): release evm 1.2.0
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending

#518 chore(main): release bitcoin 1.0.0
  packages/bitcoin/CHANGELOG.md
  release-please/rp-bitcoin-manifest.json
Labels: autorelease: pending

#515 chore(main): release utils 1.2.0
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  release-please/rp-utils-manifest.json
Labels: autorelease: pending

#520 fix: import for utils on core package
  packages/core/src/multicall.ts
Labels: do not merge

#523 chore(main): release core 1.2.1
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#525 chore(main): release evm 1.3.0
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending

#529 chore(main): release core 1.2.2
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#533 chore(main): release utils 1.2.1
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  release-please/rp-utils-manifest.json
Labels: autorelease: tagged

#538 chore(main): release evm 1.3.1
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending

#542 chore(main): release core 1.2.3
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#544 chore(main): release evm 1.3.2
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending

#550 chore(main): release evm 1.3.3
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending

#552 chore(main): release core 1.3.0
  packages/core/CHANGELOG.md
  packages/core/package.json
  release-please/rp-core-manifest.json
Labels: autorelease: pending

#553 chore(main): release evm 1.4.0
  packages/evm/CHANGELOG.md
  packages/evm/package.json
  release-please/rp-evm-manifest.json
Labels: autorelease: pending
